booking(booking).
buy(buy).
dwelling(dwelling).
earning(earning).
feeling(feeling).
follow(follow).
freezing(freezing).
give(give).
holding(holding).
leave(leave).
lighting(lighting).
positioning(positioning).
programming(programming).
recording(recording).
say(say).
take(take).
thinking(thinking).
this_morning(this_morning).
tuesday_morning(tuesday_morning).
warning(warning).
aaron(aaron).
abdulaziz_bin_salman(abdulaziz_bin_salman).
ability(ability).
abqaiq(abqaiq).
absence(absence).
absorption(absorption).
abuse(abuse).
acceleration(acceleration).
access(access).
accommodation(accommodation).
accomplishment(accomplishment).
accord(accord).
accordance(accordance).
account(account).
accountant(accountant).
accounting(accounting).
accounts(accounts).
achievement(achievement).
acquisition(acquisition).
acre(acre).
act(act).
action(action).
activities(activities).
activity(activity).
ad(ad).
adarga(adarga).
addition(addition).
address(address).
address_bank_of_america_merrill_lynch_transportation_conference(address_bank_of_america_merrill_lynch_transportation_conference).
administration(administration).
administrator(administrator).
adobe(adobe).
adoption(adoption).
advertisement(advertisement).
advice(advice).
adviser(adviser).
aep(aep).
aerie_pharmaceuticals(aerie_pharmaceuticals).
affordability(affordability).
africa(africa).
age(age).
agency(agency).
agent(agent).
agnd(agnd).
agreement(agreement).
aid(aid).
aim(aim).
air(air).
air_canada(air_canada).
airline(airline).
airtours(airtours).
alberta(alberta).
alex_waislitz(alex_waislitz).
allegation(allegation).
alliance(alliance).
alliances(alliances).
allocation(allocation).
allotment(allotment).
allowance(allowance).
alphabet(alphabet).
aluminum(aluminum).
amendment(amendment).
america(america).
amount(amount).
analysis(analysis).
analyst(analyst).
analysts(analysts).
ancr(ancr).
andrew_davies(andrew_davies).
andrew_micallef(andrew_micallef).
animalcare_group_plc(animalcare_group_plc).
announcement(announcement).
annual_general_meeting_of_the_company(annual_general_meeting_of_the_company).
antigua(antigua).
anyone(anyone).
anything(anything).
apartment(apartment).
app(app).
apparatus(apparatus).
apparel(apparel).
appetite(appetite).
apple(apple).
application(application).
appointment(appointment).
approach(approach).
approval(approval).
april_1(april_1).
april_2019(april_2019).
apy(apy).
aqn(aqn).
arbitrage(arbitrage).
architect(architect).
area(area).
arop_trading_and_investment_company_ltd(arop_trading_and_investment_company_ltd).
arrangement(arrangement).
array(array).
arrears(arrears).
art(art).
articles(articles).
artifact(artifact).
ascent(ascent).
asia(asia).
asia_pacific_region(asia_pacific_region).
aspiration(aspiration).
assessment(assessment).
assessor(assessor).
asset(asset).
assets(assets).
association(association).
atm(atm).
attack(attack).
attempt(attempt).
attention(attention).
attorney(attorney).
attraction(attraction).
auction(auction).
audit(audit).
audits(audits).
august(august).
august_2016(august_2016).
august_2018(august_2018).
aunt(aunt).
auspices(auspices).
australia(australia).
author(author).
authority(authority).
automation(automation).
autozone_inc(autozone_inc).
avail(avail).
availability(availability).
avoidance(avoidance).
award(award).
axel_heinrich(axel_heinrich).
b(b).
b2gold(b2gold).
backdrop(backdrop).
background(background).
backstop(backstop).
bahamas(bahamas).
bailout(bailout).
balance(balance).
ballot(ballot).
ban(ban).
band(band).
banjul(banjul).
banjul_international_airport(banjul_international_airport).
bank(bank).
bank_of_america_corp(bank_of_america_corp).
bank_of_russia(bank_of_russia).
banker(banker).
banking(banking).
bankruptcy(bankruptcy).
banks(banks).
bar(bar).
barber_steel_foundry(barber_steel_foundry).
barn(barn).
barrel(barrel).
barrister(barrister).
base(base).
basis(basis).
bat(bat).
bathroom(bathroom).
batteries(batteries).
bbgi(bbgi).
beating(beating).
behalf(behalf).
bell(bell).
bellamy(bellamy).
belongings(belongings).
beneficiaries(beneficiaries).
beneficiary(beneficiary).
benefit(benefit).
benefits(benefits).
bet(bet).
betakit(betakit).
beverage(beverage).
bezos(bezos).
bharti_airtel(bharti_airtel).
bid(bid).
bildt(bildt).
bill(bill).
billabong_creek(billabong_creek).
billion_hours(billion_hours).
biomass(biomass).
biosciences(biosciences).
bit(bit).
bitcoin(bitcoin).
bite(bite).
bkd(bkd).
blackrock(blackrock).
bln(bln).
blockchain(blockchain).
bloomberg(bloomberg).
blowup(blowup).
bmv(bmv).
bmw(bmw).
board(board).
board_of_directors(board_of_directors).
boj(boj).
bombing(bombing).
bond(bond).
bondholders(bondholders).
bonus(bonus).
boom(boom).
boomer(boomer).
boost(boost).
boris_johnson(boris_johnson).
boss(boss).
bout(bout).
brand(brand).
brands(brands).
breach(breach).
break(break).
brexit(brexit).
brian_ross_newman(brian_ross_newman).
brian_strutton(brian_strutton).
brikama(brikama).
brink(brink).
britain(britain).
british_airline_pilots_association(british_airline_pilots_association).
british_columbians(british_columbians).
bruce_hockman(bruce_hockman).
brunt(brunt).
bsnl(bsnl).
budget(budget).
buffalo(buffalo).
build(build).
building(building).
bumper(bumper).
bundesbank(bundesbank).
burden(burden).
bureau(bureau).
bureaucracy(bureaucracy).
business(business).
business_plan(business_plan).
businesses(businesses).
buyback(buyback).
buyer(buyer).
byron(byron).
c(c).
caa(caa).
cabal(cabal).
cabinet(cabinet).
cag(cag).
calabar(calabar).
california(california).
campaign(campaign).
canberra(canberra).
candidacy(candidacy).
cannabis(cannabis).
cap(cap).
capabilities(capabilities).
capacity(capacity).
capita(capita).
capital(capital).
capitalization(capitalization).
caption(caption).
card(card).
care(care).
career(career).
carige(carige).
carmaker(carmaker).
carrier(carrier).
case(case).
cash(cash).
casino(casino).
castle_creek_pharmaceuticals(castle_creek_pharmaceuticals).
catalano(catalano).
catalyst(catalyst).
category(category).
cavan(cavan).
cell(cell).
cent(cent).
center(center).
central_new_york_business_journal(central_new_york_business_journal).
centre(centre).
centres(centres).
century_bancorp(century_bancorp).
ceo(ceo).
cerecor(cerecor).
certificate(certificate).
cess(cess).
chain(chain).
challenge(challenge).
chance(chance).
change(change).
channel(channel).
chaos(chaos).
chart(chart).
chart_industries(chart_industries).
cheese(cheese).
chexsystems(chexsystems).
chief(chief).
child(child).
children(children).
chile(chile).
china(china).
chip(chip).
chloe(chloe).
choice(choice).
christmas_in_2017(christmas_in_2017).
cigarette(cigarette).
cinemark(cinemark).
circumstance(circumstance).
cities(cities).
citizen(citizen).
citizenship(citizenship).
city(city).
civil_aviation_authority(civil_aviation_authority).
claim(claim).
clarification(clarification).
clarity(clarity).
class(class).
classroom(classroom).
classrooms(classrooms).
client(client).
climate(climate).
closing(closing).
clothing(clothing).
cloud(cloud).
cnbc(cnbc).
coalition(coalition).
coast(coast).
code(code).
coffer(coffer).
cohesion(cohesion).
coincheck(coincheck).
collaboration(collaboration).
collapse(collapse).
collateral(collateral).
collection(collection).
collector(collector).
college(college).
combination(combination).
comment(comment).
commerce(commerce).
commission(commission).
commitment(commitment).
committee(committee).
communication(communication).
communications(communications).
communism(communism).
communities(communities).
community(community).
companies(companies).
company(company).
compensation(compensation).
competition(competition).
competitiveness(competitiveness).
complaint(complaint).
completion(completion).
compliance(compliance).
component(component).
concern(concern).
concurrent_technologies_plc(concurrent_technologies_plc).
condition(condition).
conference(conference).
confidence(confidence).
conflict(conflict).
congress(congress).
congressional_budget_office(congressional_budget_office).
conjunction(conjunction).
consideration(consideration).
construction(construction).
consumer(consumer).
consumer_action_law_centre(consumer_action_law_centre).
consumption(consumption).
content(content).
contents_finance(contents_finance).
context(context).
contingent(contingent).
contract(contract).
contrast(contrast).
contribution(contribution).
control(control).
cooper(cooper).
coordination(coordination).
copay(copay).
copper(copper).
corporation(corporation).
cosco_shipping_tanker(cosco_shipping_tanker).
cosco_shipping_tanker_dalian(cosco_shipping_tanker_dalian).
cost(cost).
council(council).
councillors(councillors).
councils(councils).
count(count).
counter(counter).
countries(countries).
country(country).
countryside(countryside).
couple(couple).
course(course).
court(court).
coventry(coventry).
cover(cover).
crash(crash).
credit(credit).
creditor(creditor).
creditors(creditors).
credits(credits).
crete(crete).
crewe(crewe).
crime(crime).
crises(crises).
crisil(crisil).
crisis(crisis).
crop(crop).
crore(crore).
crores(crores).
crowdstreet(crowdstreet).
cruiser(cruiser).
crunch(crunch).
cryptocurrencies(cryptocurrencies).
cryptocurrency(cryptocurrency).
csx(csx).
csx_news(csx_news).
culmination(culmination).
culture(culture).
curb(curb).
currency(currency).
customer(customer).
customers(customers).
customers_bancorp(customers_bancorp).
cut(cut).
cuts(cuts).
cycle(cycle).
dalasi(dalasi).
damage(damage).
damme_alexandre_van(damme_alexandre_van).
danger(danger).
danske_bank(danske_bank).
dashboard(dashboard).
data(data).
database(database).
datapoint(datapoint).
date(date).
daughter(daughter).
day(day).
deactivation(deactivation).
deadline(deadline).
%deal(deal).
death(death).
debate(debate).
debit(debit).
debt(debt).
debts(debts).
decade(decade).
december(december).
december_2013(december_2013).
decision(decision).
declare(declare).
decline(decline).
decrease(decrease).
deductibles(deductibles).
deduction(deduction).
deductions(deductions).
default(default).
deficit(deficit).
deforestation(deforestation).
delay(delay).
deliveries(deliveries).
demand(demand).
department(department).
department_for_transport(department_for_transport).
department_for_transport_and_civil_aviation_authority(department_for_transport_and_civil_aviation_authority).
department_of_human_services(department_of_human_services).
dependence(dependence).
deposit(deposit).
depreciation(depreciation).
design(design).
desire(desire).
destination(destination).
detail(detail).
developer(developer).
development(development).
devos(devos).
dgr(dgr).
diamond_bank(diamond_bank).
dickies(dickies).
diet(diet).
difference(difference).
difficulties(difficulties).
digression(digression).
dip(dip).
diplomat(diplomat).
direction(direction).
directive(directive).
director(director).
disaster(disaster).
discontent(discontent).
discount(discount).
discounting(discounting).
discussion(discussion).
disease(disease).
disillusion(disillusion).
disposal(disposal).
dispute(dispute).
distribution(distribution).
distributions(distributions).
distributor(distributor).
district(district).
diversification(diversification).
dividend(dividend).
dividends(dividends).
division(division).
divisor(divisor).
divorce(divorce).
dk_joshi(dk_joshi).
dlf(dlf).
dollar(dollar).
domain_ceo(domain_ceo).
doug_donaldson(doug_donaldson).
dow_jones_industrial_average(dow_jones_industrial_average).
downtown(downtown).
downturn(downturn).
draper_oakwood_technology_acquisition(draper_oakwood_technology_acquisition).
dream(dream).
dream_global(dream_global).
drive(drive).
driver(driver).
drones(drones).
drop(drop).
dublin(dublin).
dup(dup).
durkan(durkan).
duties(duties).
dutoit_group(dutoit_group).
dweller(dweller).
dynamics(dynamics).
earn(earn).
earnings(earnings).
ease(ease).
eastern_seaboard(eastern_seaboard).
ebitda(ebitda).
ecb(ecb).
economies(economies).
economist(economist).
economy(economy).
education(education).
education_department(education_department).
effect(effect).
effectiveness(effectiveness).
effort(effort).
eighteen_months(eighteen_months).
election(election).
electricity(electricity).
element(element).
elliott_management(elliott_management).
email(email).
emission(emission).
empire(empire).
employee(employee).
employer(employer).
employers(employers).
end(end).
energy(energy).
enerplus(enerplus).
enerplus_corp(enerplus_corp).
engineer(engineer).
engineering(engineering).
england(england).
enterprise(enterprise).
entities(entities).
entity(entity).
entrepreneur(entrepreneur).
entry(entry).
environment(environment).
ep(ep).
eps(eps).
equipment(equipment).
equities(equities).
equity(equity).
er(er).
era(era).
erf(erf).
escape(escape).
establishment(establishment).
estatement(estatement).
estimate(estimate).
etf(etf).
etr(etr).
eu_general_data_protection_regulation(eu_general_data_protection_regulation).
europe(europe).
european_central_bank(european_central_bank).
european_union(european_union).
event(event).
everyone(everyone).
everything(everything).
evidence(evidence).
example(example).
exception(exception).
excess(excess).
exchange(exchange).
exclusion(exclusion).
executive(executive).
exemption(exemption).
exemptions(exemptions).
exit(exit).
exodus(exodus).
expansion(expansion).
expectation(expectation).
expectations(expectations).
expenditure(expenditure).
expense(expense).
expenses(expenses).
experience(experience).
expert(expert).
experts(experts).
exploration(exploration).
explorer(explorer).
export(export).
exporter(exporter).
exports(exports).
exposure(exposure).
ext(ext).
extension(extension).
extent(extent).
face(face).
facebook(facebook).
facebook_share(facebook_share).
facebook_twitter_google(facebook_twitter_google).
facilities(facilities).
facility(facility).
fact(fact).
factor(factor).
factories(factories).
factory(factory).
factset(factset).
failure(failure).
fall(fall).
families(families).
family(family).
fan(fan).
fannie(fannie).
fares(fares).
farmer(farmer).
farmers(farmers).
farmland_assessment_act(farmland_assessment_act).
fat(fat).
favour(favour).
fc(fc).
fd(fd).
fear(fear).
february_2017(february_2017).
federal_government(federal_government).
federal_ministry_of_petroleum_resources(federal_ministry_of_petroleum_resources).
federal_reserve(federal_reserve).
fee(fee).
feed(feed).
feedback(feedback).
fees(fees).
felicity_emmett(felicity_emmett).
fertiliser(fertiliser).
fhfa(fhfa).
fiance(fiance).
fidelity(fidelity).
field(field).
figure(figure).
file(file).
filing(filing).
filings(filings).
film(film).
finalist(finalist).
finance(finance).
finances(finances).
financial_ombudsman_service(financial_ombudsman_service).
financing(financing).
fire(fire).
firm(firm).
first_division(first_division).
first_quarter(first_quarter).
first_quarter_2020(first_quarter_2020).
fiserv(fiserv).
fish(fish).
fisheries_regulations(fisheries_regulations).
fite(fite).
fleischer(fleischer).
flexibility(flexibility).
flight(flight).
floor(floor).
florida(florida).
flotation(flotation).
flow(flow).
flurry(flurry).
fncl(fncl).
folk(folk).
food(food).
forecast(forecast).
forecasts(forecasts).
forest(forest).
form(form).
fortune(fortune).
fortune_india(fortune_india).
foster(foster).
fosun(fosun).
founder(founder).
fourth_quarter_2018(fourth_quarter_2018).
fpd(fpd).
frame(frame).
franchise(franchise).
fraud(fraud).
freddie(freddie).
freedom(freedom).
frequency(frequency).
friday(friday).
fruit(fruit).
fscs(fscs).
ft(ft).
fuel(fuel).
fund(fund).
funding(funding).
funds(funds).
future(future).
gain(gain).
gambia(gambia).
gambia_port_authority(gambia_port_authority).
gamble(gamble).
game(game).
games_workshop_group_plc(games_workshop_group_plc).
gap(gap).
gasoline(gasoline).
gaw(gaw).
gbx(gbx).
gdp(gdp).
gebre(gebre).
gencanna(gencanna).
generation(generation).
geography(geography).
germany(germany).
getty_images_the_federal_reserve(getty_images_the_federal_reserve).
giant(giant).
gift(gift).
gilead_sciences(gilead_sciences).
glaciers(glaciers).
global_investment_house(global_investment_house).
gloucester_county(gloucester_county).
glut(glut).
gmv(gmv).
gnl(gnl).
goa(goa).
goal(goal).
gold(gold).
goods(goods).
government(government).
grant(grant).
graph(graph).
greeks(greeks).
grievance(grievance).
group(group).
grower(grower).
growth(growth).
gst(gst).
guidance(guidance).
guide(guide).
guideline(guideline).
györgy_matolcsy(györgy_matolcsy).
half(half).
hammer_capital(hammer_capital).
hamriya_free_zone(hamriya_free_zone).
hand(hand).
harlequin(harlequin).
haven(haven).
hawk(hawk).
head(head).
headcount(headcount).
headline(headline).
headlines(headlines).
headwind(headwind).
healthcare(healthcare).
hearing(hearing).
heartlandnews(heartlandnews).
hedge(hedge).
height(height).
helen_sabzevari(helen_sabzevari).
hell(hell).
help(help).
help_to_buy_isa(help_to_buy_isa).
heraklion_airport(heraklion_airport).
hersha_hospitality_trust(hersha_hospitality_trust).
highlight(highlight).
hilux(hilux).
hint(hint).
history(history).
hit(hit).
hkex(hkex).
hmb(hmb).
hold(hold).
holder(holder).
holdings_ltd(holdings_ltd).
hole(hole).
holiday(holiday).
holidays(holidays).
home(home).
homebuilders(homebuilders).
hope(hope).
horse(horse).
host(host).
hotel_merrion_ltd(hotel_merrion_ltd).
hour(hour).
house(house).
household(household).
housing(housing).
hs2(hs2).
hsa(hsa).
ht(ht).
hub(hub).
hubbard(hubbard).
hunter_harrison(hunter_harrison).
husband(husband).
hypothesis(hypothesis).
i(i).
ice(ice).
iceland(iceland).
icelandic_meteorological_office(icelandic_meteorological_office).
idea(idea).
ideology(ideology).
illiquidity(illiquidity).
image(image).
images(images).
impact(impact).
impairment(impairment).
implosion(implosion).
import(import).
importance(importance).
importer(importer).
imports(imports).
improvement(improvement).
inaction(inaction).
inauguration(inauguration).
inbox(inbox).
incentive(incentive).
incidence(incidence).
inclination(inclination).
income(income).
income_trust_plc(income_trust_plc).
increase(increase).
india(india).
indicator(indicator).
industrial_park(industrial_park).
industrialisation(industrialisation).
industry(industry).
inequality(inequality).
inflation(inflation).
inflow(inflow).
information(information).
infrastructure(infrastructure).
initialized_capital(initialized_capital).
initiative(initiative).
injection(injection).
innovation(innovation).
inovia(inovia).
insider(insider).
insiders(insiders).
insight(insight).
insolvency(insolvency).
insolvency_service(insolvency_service).
inspire(inspire).
instagram(instagram).
instance(instance).
instrument(instrument).
insurance(insurance).
integration(integration).
intel(intel).
interest(interest).
internal_revenue_service(internal_revenue_service).
international_monetary_fund(international_monetary_fund).
internet(internet).
intrexon(intrexon).
introduction(introduction).
inventories(inventories).
inventory(inventory).
invesco_emerging_markets_ultra_dividend_revenue_etf(invesco_emerging_markets_ultra_dividend_revenue_etf).
investigation(investigation).
investment(investment).
investments(investments).
investor(investor).
investors(investors).
invitation(invitation).
invoice(invoice).
involvement(involvement).
iphone(iphone).
ipo(ipo).
iq(iq).
ira(ira).
ireland(ireland).
irma(irma).
irr(irr).
isd(isd).
island(island).
island_institute(island_institute).
issuance(issuance).
issue(issue).
issuers(issuers).
ita(ita).
item(item).
jamie_oliver(jamie_oliver).
january(january).
january_1990_1500(january_1990_1500).
january_2017(january_2017).
japan(japan).
jcs(jcs).
jd(jd).
jeff_bezos(jeff_bezos).
jens_reckendorf(jens_reckendorf).
jerash_holdings(jerash_holdings).
jimmy_john(jimmy_john).
jmmb_group(jmmb_group).
jmmbgl(jmmbgl).
joanie(joanie).
job(job).
jobs(jobs).
joint_venture_agreement(joint_venture_agreement).
josh_frydenberg(josh_frydenberg).
jp_morgan(jp_morgan).
jp_morgan_chase(jp_morgan_chase).
judge(judge).
judgment(judgment).
july(july).
july_1(july_1).
july_19(july_19).
july_2005(july_2005).
july_2018(july_2018).
july_8(july_8).
june(june).
june_2019(june_2019).
june_23_this_year(june_23_this_year).
justina_vasquez(justina_vasquez).
k(k).
kabwe(kabwe).
kaepernick(kaepernick).
kaiser_family_foundation(kaiser_family_foundation).
kamco_investment_company(kamco_investment_company).
kate_rankin(kate_rankin).
kathleen_kraninger(kathleen_kraninger).
kerch_strait(kerch_strait).
key(key).
kforce(kforce).
kharagpur(kharagpur).
khartoum(khartoum).
khc(khc).
kingdom(kingdom).
kkr(kkr).
kkt(kkt).
knight(knight).
kraft_heinz_co(kraft_heinz_co).
label(label).
labor(labor).
lack(lack).
lagos(lagos).
land(land).
landfill(landfill).
landmark(landmark).
laos(laos).
larry_nassar(larry_nassar).
last_20_years(last_20_years).
last_90_days(last_90_days).
last_decade(last_decade).
last_september(last_september).
late_march(late_march).
launch(launch).
law(law).
law_on_water_resources(law_on_water_resources).
laws(laws).
lawsuit(lawsuit).
layton_roche(layton_roche).
leader(leader).
lease(lease).
lebanon(lebanon).
leg(leg).
legislation(legislation).
lender(lender).
lessor(lessor).
letter(letter).
letter_of_authority(letter_of_authority).
level(level).
lever(lever).
leverage(leverage).
levies(levies).
levy(levy).
liabilities(liabilities).
liability(liability).
licensing(licensing).
life(life).
likes(likes).
limit(limit).
line(line).
lion(lion).
liquid(liquid).
liquidation(liquidation).
liquidity(liquidity).
list(list).
literature(literature).
livelihood(livelihood).
llc(llc).
loan(loan).
loans(loans).
lockheed(lockheed).
lockheed_martin(lockheed_martin).
lon(lon).
lon_ancr(lon_ancr).
london(london).
look(look).
loser(loser).
%loss(loss).
losses(losses).
lot(lot).
loughborough(loughborough).
lse(lse).
lts(lts).
lufthansa(lufthansa).
m(m).
machinery(machinery).
mackey(mackey).
mainland(mainland).
maintenance(maintenance).
majority(majority).
maker(maker).
malawi(malawi).
malaysia(malaysia).
man(man).
management(management).
manchester(manchester).
mandate(mandate).
manhattan(manhattan).
manufacturer(manufacturer).
manufacturers(manufacturers).
manufacturing(manufacturing).
march_2001_1500(march_2001_1500).
march_2017(march_2017).
march_2018(march_2018).
march_2023(march_2023).
march_29th(march_29th).
march_of_this_year(march_of_this_year).
march_quarter(march_quarter).
mare(mare).
marijuana(marijuana).
market(market).
marketing(marketing).
marketplace(marketplace).
marvell_technology_group(marvell_technology_group).
masterplan(masterplan).
mat(mat).
material(material).
maternity(maternity).
mathias_cormann(mathias_cormann).
matter(matter).
maturities(maturities).
maturity(maturity).
maximum(maximum).
may_2003(may_2003).
may_2018(may_2018).
mckinsey(mckinsey).
mean(mean).
means(means).
measure(measure).
media(media).
medicare(medicare).
medication(medication).
medikabazaar(medikabazaar).
meet(meet).
meeting(meeting).
melbourne(melbourne).
member(member).
mengniu(mengniu).
merchandising(merchandising).
merchant(merchant).
merger(merger).
merit(merit).
merkel(merkel).
metal(metal).
mfnc(mfnc).
mfs_municipal_income_trust(mfs_municipal_income_trust).
micro(micro).
middle_east(middle_east).
midf_investment_bank(midf_investment_bank).
midnight(midnight).
midwest_regional_educational_service_center(midwest_regional_educational_service_center).
migrant(migrant).
mike(mike).
mike_ashley(mike_ashley).
mike_novogratz(mike_novogratz).
mile(mile).
milestone(milestone).
mill(mill).
millennial(millennial).
million_euro(million_euro).
million_gallons(million_gallons).
million_pound(million_pound).
million_pounds(million_pounds).
millionaire(millionaire).
mine(mine).
minimum(minimum).
minister(minister).
ministry_of_finance(ministry_of_finance).
ministry_of_manpower(ministry_of_manpower).
ministry_of_petroleum_and_energy(ministry_of_petroleum_and_energy).
misclassification(misclassification).
mishandle(mishandle).
missile(missile).
mission(mission).
mix(mix).
mlp(mlp).
mo(mo).
moan(moan).
model(model).
mohammed_yusuf_share(mohammed_yusuf_share).
momentum(momentum).
monarch_airlines(monarch_airlines).
monday(monday).
monex(monex).
money(money).
month(month).
months(months).
morning(morning).
mortgage(mortgage).
mother(mother).
motion(motion).
move(move).
movement(movement).
mover(mover).
mr(mr).
mrg(mrg).
mri(mri).
mrvl(mrvl).
msci_usa_equal_weighted_etf(msci_usa_equal_weighted_etf).
mubasher(mubasher).
mufg(mufg).
multinationals(multinationals).
municipalities(municipalities).
musk(musk).
mvr(mvr).
n1(n1).
n100_million(n100_million).
n3(n3).
n354(n354).
n364(n364).
n365(n365).
n5(n5).
n563billion(n563billion).
n823billion(n823billion).
nail(nail).
nairobi(nairobi).
name(name).
nasdaq(nasdaq).
naspers(naspers).
nation(nation).
national_association_of_realtors(national_association_of_realtors).
national_broadband_network(national_broadband_network).
national_consumer_empowerment_conference(national_consumer_empowerment_conference).
national_nutrition_agency(national_nutrition_agency).
national_savings_and_investments(national_savings_and_investments).
national_transport_policy(national_transport_policy).
nature(nature).
ndis(ndis).
need(need).
netherlands(netherlands).
network(network).
networks(networks).
new_delhi(new_delhi).
new_york(new_york).
new_york_city(new_york_city).
new_york_times(new_york_times).
new_zealand(new_zealand).
news(news).
newsletter(newsletter).
next_10_years(next_10_years).
ngl(ngl).
ngl_energy_partners_lp(ngl_energy_partners_lp).
nike(nike).
nike_inc(nike_inc).
ninety_days(ninety_days).
nio(nio).
nirmala_sitharaman(nirmala_sitharaman).
nomura(nomura).
none(none).
norm(norm).
north_america(north_america).
note(note).
nothing(nothing).
notice(notice).
november(november).
numbers(numbers).
nyse(nyse).
nyse_szc(nyse_szc).
nyse_tkr(nyse_tkr).
nysearca(nysearca).
nysearca_ryf(nysearca_ryf).
oasmia_pharmaceutical_ab(oasmia_pharmaceutical_ab).
objective(objective).
obligation(obligation).
obstacle(obstacle).
occupation(occupation).
ocean(ocean).
october(october).
october_1(october_1).
october_11th(october_11th).
october_2018(october_2018).
october_31st(october_31st).
oecd(oecd).
ofac(ofac).
offer(offer).
offering(offering).
offeror(offeror).
office(office).
office_for_budget_responsibility(office_for_budget_responsibility).
officer(officer).
official(official).
officials(officials).
offload(offload).
offshor(offshor).
oil(oil).
olive_garden(olive_garden).
olympia_financial_group_inc(olympia_financial_group_inc).
ombudsman(ombudsman).
omo(omo).
one_month(one_month).
one_thousand(one_thousand).
one_year(one_year).
ontario(ontario).
opening(opening).
operation(operation).
operation_matterhorn(operation_matterhorn).
operator(operator).
oppenheimer(oppenheimer).
opportunities(opportunities).
opportunity(opportunity).
optimism(optimism).
option(option).
orban(orban).
order(order).
orders(orders).
ordinance(ordinance).
ore(ore).
organization(organization).
organization_for_economic_cooperation_and_development(organization_for_economic_cooperation_and_development).
ounce(ounce).
outcome(outcome).
outfit(outfit).
outline(outline).
outlook(outlook).
outperform(outperform).
output(output).
overhead(overhead).
overstock(overstock).
owner(owner).
pace(pace).
package(package).
page(page).
pak(pak).
paper(paper).
papua_new_guinea(papua_new_guinea).
paragraph(paragraph).
parent(parent).
park(park).
parliament(parliament).
part(part).
participation(participation).
parties(parties).
partner(partner).
partnership(partnership).
passenger(passenger).
passengers(passengers).
past(past).
past_quarter(past_quarter).
patents(patents).
paternity(paternity).
pathway(pathway).
paul(paul).
paulson(paulson).
payment(payment).
pea(pea).
peace(peace).
peak(peak).
peer(peer).
penalties(penalties).
penalty(penalty).
pence(pence).
penn_state_board_of_trustees_committee_on_finance(penn_state_board_of_trustees_committee_on_finance).
pension(pension).
people(people).
percent(percent).
percentage(percentage).
performance(performance).
period(period).
permission(permission).
person(person).
personnel(personnel).
perspecta(perspecta).
perspecta_inc(perspecta_inc).
pet(pet).
petroleum_oil_blocks(petroleum_oil_blocks).
pff(pff).
pgim_high_yield_bond_fund_inc(pgim_high_yield_bond_fund_inc).
photo(photo).
photograph(photograph).
photographer(photographer).
piece(piece).
piyush_goyal(piyush_goyal).
pjt(pjt).
pjt_partners(pjt_partners).
pjt_partners_inc(pjt_partners_inc).
pk(pk).
place(place).
placement(placement).
placementtracker(placementtracker).
plan(plan).
plane(plane).
planes(planes).
planning_solutions_group_llc(planning_solutions_group_llc).
planning_solutions_group_llc_boosts_stake_in_vanguard(planning_solutions_group_llc_boosts_stake_in_vanguard).
plans(plans).
plant(plant).
plantation(plantation).
platform(platform).
platinum(platinum).
player(player).
plc(plc).
plot(plot).
point(point).
police(police).
policies(policies).
policy(policy).
politician(politician).
politics(politics).
pollution(pollution).
polyhalite(polyhalite).
popularise(popularise).
popularity(popularity).
population(population).
populism(populism).
pork(pork).
port(port).
portelli(portelli).
portfolio(portfolio).
portion(portion).
position(position).
post(post).
potsdam(potsdam).
pound(pound).
powder(powder).
power(power).
pp(pp).
practice(practice).
premium(premium).
preparations(preparations).
prescription(prescription).
presentation(presentation).
president(president).
press(press).
pressure(pressure).
price(price).
priorities(priorities).
privilege(privilege).
pro(pro).
probe(probe).
problem(problem).
procedure(procedure).
proceeds(proceeds).
process(process).
processing(processing).
processor(processor).
producer(producer).
product(product).
production(production).
products(products).
profession(profession).
profile(profile).
profit(profit).
profitability(profitability).
profits(profits).
program(program).
programme(programme).
programs(programs).
progress(progress).
progression(progression).
project(project).
projects(projects).
properties(properties).
property(property).
propetro(propetro).
proportion(proportion).
proposal(proposal).
proposition(proposition).
proprietor(proprietor).
prorogation(prorogation).
prosecutor(prosecutor).
prosecutors(prosecutors).
prospects(prospects).
protections(protections).
provider(provider).
province(province).
provision(provision).
psf(psf).
pti(pti).
public(public).
publisher(publisher).
pull(pull).
pump(pump).
purchase(purchase).
purchases(purchases).
purpose(purpose).
purse(purse).
push(push).
q2(q2).
q4(q4).
qatar_investment_authority(qatar_investment_authority).
quarrels(quarrels).
quarter(quarter).
quest(quest).
question(question).
race(race).
rad(rad).
radar(radar).
radius(radius).
raft(raft).
raghuram_rajan(raghuram_rajan).
raise(raise).
rally(rally).
ramification(ramification).
rana_huzefa(rana_huzefa).
range(range).
ratchet(ratchet).
rate(rate).
rates(rates).
rating(rating).
ratio(ratio).
rba(rba).
rbi(rbi).
re(re).
reading(reading).
readmore(readmore).
reality(reality).
reason(reason).
reassessment(reassessment).
receipt(receipt).
receipts(receipts).
receiver(receiver).
recession(recession).
recommendation(recommendation).
recommendations(recommendations).
record(record).
reduction(reduction).
refiner(refiner).
refinery(refinery).
refinitiv(refinitiv).
reform(reform).
refugee(refugee).
refunds(refunds).
refurbishment(refurbishment).
regard(regard).
regime(regime).
regulation(regulation).
regulator(regulator).
reit(reit).
rejection(rejection).
rejuvenation(rejuvenation).
relation(relation).
relative(relative).
release(release).
reliance(reliance).
relief(relief).
remain(remain).
remittance(remittance).
remuneration(remuneration).
renewal(renewal).
rent(rent).
reorganization(reorganization).
repair(repair).
repatriation(repatriation).
reply(reply).
report(report).
reporter(reporter).
reporting(reporting).
reports(reports).
representation(representation).
representative(representative).
repsol_sa(repsol_sa).
republic(republic).
republic_of_congo(republic_of_congo).
repurchase(repurchase).
request(request).
requirement(requirement).
research(research).
reserve(reserve).
reserve_bank_of_india(reserve_bank_of_india).
residence(residence).
resident(resident).
residents(residents).
resolution(resolution).
resource(resource).
resources(resources).
response(response).
rest(rest).
restoration(restoration).
restructuring(restructuring).
result(result).
retailer(retailer).
retiree(retiree).
retirement(retirement).
return(return).
revenue(revenue).
revenues(revenues).
revert(revert).
review(review).
revolution(revolution).
rhetoric(rhetoric).
ride(ride).
rights(rights).
ripple(ripple).
rise(rise).
risk(risk).
rival(rival).
river(river).
road(road).
roark_capital(roark_capital).
role(role).
romania(romania).
romaniainsider(romaniainsider).
rothbury(rothbury).
rothmans(rothmans).
round(round).
routemaster(routemaster).
routes(routes).
royal(royal).
rts(rts).
rubber_board(rubber_board).
rubie(rubie).
rule(rule).
ruling(ruling).
rusal(rusal).
ruth_ann_marshall(ruth_ann_marshall).
rwr(rwr).
ryan_kenny(ryan_kenny).
ryt(ryt).
safety(safety).
saga(saga).
salaries(salaries).
sale(sale).
sales(sales).
sanction(sanction).
saturday(saturday).
saudi_arabia(saudi_arabia).
savings(savings).
scale(scale).
scandal(scandal).
scarcity(scarcity).
scene(scene).
schedule(schedule).
scheme(scheme).
school(school).
schoolgirl(schoolgirl).
science(science).
scoop(scoop).
scrap(scrap).
sea(sea).
season(season).
sec(sec).
second_quarter(second_quarter).
second_quarter_2019(second_quarter_2019).
sector(sector).
securities_and_exchange_commission(securities_and_exchange_commission).
security(security).
security_national_bank_of_sioux_city_iowa_ia(security_national_bank_of_sioux_city_iowa_ia).
segment(segment).
seizert_capital_partners_llc(seizert_capital_partners_llc).
sense(sense).
sensex(sensex).
sentiment(sentiment).
sept_24(sept_24).
september(september).
september_2018(september_2018).
september_30th(september_30th).
series(series).
server(server).
service(service).
services(services).
session(session).
seth_golden(seth_golden).
settlement(settlement).
shakeout(shakeout).
shaktikanta_das(shaktikanta_das).
share(share).
shareholder(shareholder).
shareholders(shareholders).
shares(shares).
sheet(sheet).
shift(shift).
ship(ship).
shipping(shipping).
shock(shock).
shop(shop).
shopper(shopper).
shortfall(shortfall).
sidney(sidney).
sidney_hometown_investments(sidney_hometown_investments).
sierra_leone(sierra_leone).
sign(sign).
signal(signal).
silver(silver).
simba(simba).
simon_goodley(simon_goodley).
singapore(singapore).
singapore_exchange(singapore_exchange).
sirius(sirius).
site(site).
sitharaman(sitharaman).
situation(situation).
six_months(six_months).
six_weeks(six_weeks).
size(size).
skepticism(skepticism).
skin(skin).
sky_news(sky_news).
slate(slate).
slowdown(slowdown).
smiths(smiths).
snb(snb).
sneakers(sneakers).
social_security(social_security).
society_for_human_resource_management(society_for_human_resource_management).
softbank(softbank).
software(software).
solicitors(solicitors).
solution(solution).
son(son).
sonoma_county_community_development_commission(sonoma_county_community_development_commission).
soros(soros).
source(source).
soybean(soybean).
space(space).
spain(spain).
speaker(speaker).
specialist(specialist).
spectrum(spectrum).
speech(speech).
speed(speed).
spend(spend).
spending(spending).
split(split).
spread(spread).
spur(spur).
stability(stability).
staff(staff).
stage(stage).
stake(stake).
stakeholder(stakeholder).
stakeholders(stakeholders).
standby(standby).
starbucks(starbucks).
start(start).
starter(starter).
startup(startup).
state(state).
statement(statement).
station(station).
status(status).
steam(steam).
steel_partners(steel_partners).
steer(steer).
step(step).
stigma(stigma).
stimulus(stimulus).
stock(stock).
stockholder(stockholder).
stocks(stocks).
storage(storage).
store(store).
storm(storm).
stormwater(stormwater).
story(story).
strategists(strategists).
strategy(strategy).
streak(streak).
street(street).
strength(strength).
strike(strike).
striker(striker).
structure(structure).
struggle(struggle).
student(student).
students(students).
studies(studies).
study(study).
subscriber(subscriber).
subscription(subscription).
subsidiary(subsidiary).
subsidies(subsidies).
substation(substation).
substitution(substitution).
success(success).
sudan(sudan).
sue(sue).
suite(suite).
sum(sum).
summer_in_2018(summer_in_2018).
sunday(sunday).
sunset(sunset).
supplier(supplier).
suppliers(suppliers).
supplies(supplies).
supply(supply).
support(support).
supporter(supporter).
supreme_court(supreme_court).
surc(surc).
surge(surge).
surrey(surrey).
surtax(surtax).
survey(survey).
suv(suv).
svp_irving_tan(svp_irving_tan).
sydney(sydney).
syndication(syndication).
syndications(syndications).
system(system).
table(table).
taf_africa_global(taf_africa_global).
tailwind(tailwind).
takeover(takeover).
talent(talent).
talk(talk).
tap(tap).
tariff(tariff).
task(task).
tata_metaliks(tata_metaliks).
tax(tax).
taxes(taxes).
taxi(taxi).
taxpayer(taxpayer).
taxpayers(taxpayers).
tcg(tcg).
teacher(teacher).
team(team).
technique(technique).
technologies(technologies).
technology(technology).
teens(teens).
tehran(tehran).
telent(telent).
television(television).
telocation(telocation).
tema(tema).
tencent_holdings_ltd(tencent_holdings_ltd).
tender(tender).
tension(tension).
term(term).
terminal(terminal).
termination(termination).
territory(territory).
tesla(tesla).
texas(texas).
textile(textile).
tgmedia(tgmedia).
thank(thank).
thanks(thanks).
the_first_quarter(the_first_quarter).
the_first_quarter_of_2019(the_first_quarter_of_2019).
theory(theory).
third_quarter(third_quarter).
third_quarter_of_2019(third_quarter_of_2019).
thomas_stuemmler(thomas_stuemmler).
three_months(three_months).
three_weeks(three_weeks).
three_years(three_years).
threshold(threshold).
thummel(thummel).
thursday(thursday).
ticket(ticket).
tii(tii).
timberland(timberland).
time(time).
tip(tip).
titan(titan).
tjx_companies(tjx_companies).
tjx_companies_inc(tjx_companies_inc).
today(today).
tokyo_stock_exchange(tokyo_stock_exchange).
tomorrow(tomorrow).
ton(ton).
tonne(tonne).
top(top).
torrent(torrent).
tour(tour).
tourism(tourism).
tourist(tourist).
town(town).
town_xyz(town_xyz).
toyota(toyota).
tpep(tpep).
track(track).
trade(trade).
trader(trader).
trading(trading).
tradition(tradition).
traffic(traffic).
tragedy(tragedy).
train(train).
trajectory(trajectory).
transaction(transaction).
transat(transat).
transfer(transfer).
transport(transport).
transportation(transportation).
travel(travel).
travelers_companies(travelers_companies).
travels(travels).
travelzoo(travelzoo).
treasuries(treasuries).
treasury(treasury).
treatment(treatment).
tribunal(tribunal).
trim(trim).
truck(truck).
trump(trump).
trust(trust).
tse(tse).
tuesday(tuesday).
tug(tug).
tunisia(tunisia).
turbulence(turbulence).
turkey(turkey).
turn(turn).
turnaround(turnaround).
turnover(turnover).
tv(tv).
tweet_twentyfour_select_monthly_incm_fd_ltd(tweet_twentyfour_select_monthly_incm_fd_ltd).
twelve_months(twelve_months).
twelve_years(twelve_years).
twenty_years(twenty_years).
twitter(twitter).
two_days(two_days).
two_weeks(two_weeks).
two_years(two_years).
type(type).
uber(uber).
uc(uc).
uk(uk).
uk_civil_aviation_authority(uk_civil_aviation_authority).
uk_plc(uk_plc).
uncertainties(uncertainties).
uncertainty(uncertainty).
uncle(uncle).
uniform(uniform).
union(union).
unit(unit).
united_auto_workers(united_auto_workers).
united_states(united_states).
units(units).
university(university).
unlock(unlock).
upc(upc).
upc_romania(upc_romania).
update(update).
upgrade(upgrade).
upside(upside).
upturn(upturn).
urge(urge).
usa(usa).
usda(usda).
use(use).
user(user).
users(users).
utilisation(utilisation).
utilities(utilities).
vacation(vacation).
vacations(vacations).
valuation(valuation).
value(value).
variety(variety).
vehicle(vehicle).
ventas(ventas).
vessel(vessel).
vf(vf).
viability(viability).
vibe(vibe).
victoria(victoria).
victory(victory).
vietnam(vietnam).
villa(villa).
village(village).
viola(viola).
violation(violation).
visibility(visibility).
vision_fund(vision_fund).
vivaldi_capital_management_llc(vivaldi_capital_management_llc).
vladimir_miklashevsky(vladimir_miklashevsky).
vodafone(vodafone).
volume(volume).
vote(vote).
voter(voter).
vym(vym).
wage(wage).
wagerer(wagerer).
wages(wages).
wake(wake).
war(war).
warren(warren).
washington(washington).
waste_management(waste_management).
wastewater(wastewater).
water(water).
way(way).
weakness(weakness).
wealth(wealth).
weather(weather).
web(web).
website(website).
wed(wed).
wedding(wedding).
wednesday(wednesday).
week(week).
weeks(weeks).
welfare(welfare).
west_bengal(west_bengal).
wetherspoons(wetherspoons).
wetlands(wetlands).
wife(wife).
windsor(windsor).
winter(winter).
wire(wire).
withdrawal(withdrawal).
woman(woman).
women(women).
wood(wood).
woodbine_mohawk_park(woodbine_mohawk_park).
word(word).
work(work).
worker(worker).
workers(workers).
workflow(workflow).
%works(works).
world(world).
world_bank(world_bank).
worry(worry).
worth(worth).
yamana_gold(yamana_gold).
yang(yang).
ychart(ychart).
year(year).
years(years).
yesterday(yesterday).
yield(yield).
youth(youth).
youtube(youtube).
yoy(yoy).
zamparo(zamparo).
zhejiang(zhejiang).
adhesive(adhesive).
apiece(apiece).
assembly(assembly).
atlantic(atlantic).
average(average).
back(back).
bully(bully).
complex(complex).
dalian(dalian).
derivative(derivative).
diocese(diocese).
flat(flat).
fundamental(fundamental).
high(high).
individual(individual).
intangible(intangible).
live(live).
low(low).
negative(negative).
neutral(neutral).
potential(potential).
promotional(promotional).
retail(retail).
senior(senior).
technical(technical).
there(there).
third(third).
total(total).
upward(upward).
vertical(vertical).
wantedly(wantedly).

loss(X) :- transat(X).
complete(X, Y) :- deal(X), works(Y).
deal(X) :- stock(X).
works(X) :- senior(X).
